// import React from 'react'


function TnC() {
  return (
    <div className="min-h-screen">
      <div className="">Terms and Conditions Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore dolore adipisci sequi tenetur nulla doloribus velit magnam! Doloribus maxime, architecto nostrum quam voluptate id perferendis fuga nisi, inventore excepturi quibusdam.
      Dolor optio aperiam nostrum laboriosam possimus architecto nemo cupiditate labore natus nisi, accusamus accusantium quidem voluptates recusandae excepturi consectetur quam iure consequuntur reiciendis vitae magnam commodi! Voluptatem incidunt sed fuga!
      Libero ad explicabo quibusdam dolores, excepturi delectus dignissimos voluptatibus exercitationem minus reprehenderit distinctio nulla doloremque placeat rem. Vel, iure nulla rerum nisi iste porro nobis, ipsam cupiditate quod similique repellendus?
      Maxime dolorum totam aliquid ad facilis magni molestias. Sint aperiam omnis explicabo, voluptatum provident accusamus, iusto mollitia quia repellat dicta nihil reiciendis cum est alias. Alias labore repellat vitae doloremque.
      Similique sint, voluptatem voluptates ipsum non consectetur hic commodi quidem sunt quibusdam assumenda, deserunt accusantium illo itaque facere inventore repellendus nisi debitis numquam esse nemo cum. Est iure tenetur corrupti?
      Itaque ratione veniam eaque voluptate excepturi aperiam, tempora ad consequuntur vel, eveniet rem sapiente temporibus quis. Tempore maxime nulla id amet accusamus ducimus excepturi molestias dicta, porro quasi, magnam fugiat.
      Totam, exercitationem libero soluta, sed ad iure nobis modi nulla autem eum mollitia. Ea officia rem, est earum sit ratione, cupiditate dignissimos necessitatibus provident molestiae obcaecati facere eaque unde commodi.
      Quia non quod, debitis numquam suscipit est architecto odit deserunt consequatur corporis iste nostrum neque vitae eius sed adipisci illum sequi error, alias, doloribus rem. Aspernatur vel dolores quisquam natus!
      Accusamus optio quidem architecto hic quod cumque officia consequatur unde voluptate eaque, alias autem? Nesciunt iusto, tenetur, harum tempore, cupiditate delectus maiores fuga ipsam nostrum quaerat rerum at id tempora?
      Illum voluptatum fugit facilis at laboriosam, vitae commodi perspiciatis accusamus cum similique! Sunt excepturi quis dolore veniam earum, repellendus error, modi eaque doloremque officiis fugiat ad facilis. Voluptas, accusamus voluptatem!
      Cumque, laudantium mollitia, esse quis adipisci dolore rem quaerat natus eius, distinctio autem veritatis ex tenetur repudiandae necessitatibus suscipit illum iusto alias numquam iste dolores ab minus. Eum, iusto cumque.
      Nihil, omnis quae? Repellat, laudantium inventore. Doloribus fuga, tempore voluptas vitae maxime magni minima voluptates harum? Non, suscipit maxime tempora quis hic cum, atque, ut eaque libero dolores amet! Ipsum?
      Rem quidem iure ullam sit reprehenderit mollitia animi eligendi in debitis officiis, fuga ea aspernatur. Placeat vero tempore ratione excepturi assumenda atque sit eveniet illum autem, nam ut beatae incidunt?
      Exercitationem similique aperiam ullam consequatur ex voluptatum ratione cupiditate illo fugit, sequi nihil excepturi quisquam id temporibus praesentium impedit incidunt odit voluptatem molestias ipsum hic placeat at, soluta molestiae. Explicabo.
      Eum, iusto. Cumque nemo rem porro, quia, ipsa maxime labore consequuntur eaque at, quae deserunt quibusdam similique. Quis voluptates ab neque a? Labore ad id animi? Ducimus ipsam ab neque!
      Molestiae labore, quos eveniet quae nobis distinctio cumque rem quasi saepe dicta alias repellat commodi dolore. Optio repellendus nam nihil ad eius explicabo fugit, omnis, ab voluptates nobis saepe sed?
      Voluptatibus labore ea quo consectetur fugiat, ab minus veritatis corporis? Officiis sequi voluptatem consequatur dolor consequuntur asperiores ducimus officia. Laboriosam sint veniam autem numquam illum tempora architecto sit voluptatum cum!
      Cumque ut, temporibus quos est eveniet quasi accusamus architecto labore deserunt veniam officiis reprehenderit minus beatae iure fugit veritatis dolores quo modi maxime? Vero ea amet aliquid nobis culpa! Omnis.
      Veniam excepturi deserunt consequuntur mollitia culpa, qui rerum enim quae dignissimos placeat blanditiis aliquam necessitatibus hic architecto et dolorum tempore iure libero esse debitis. Quo, voluptas? Autem minima porro inventore?
      Numquam animi maiores sapiente mollitia, commodi praesentium nemo cupiditate vitae et debitis quibusdam ipsam saepe accusamus hic inventore porro similique enim ipsum nesciunt temporibus iure. Ab pariatur autem rem. Repudiandae.
      Ullam excepturi hic molestiae veritatis dolores a repellendus, enim placeat esse tempora, aut natus vel officiis assumenda corrupti et cum eaque doloribus quo id aliquam, possimus est! Non, laboriosam repudiandae.
      Explicabo commodi minima possimus ipsum ea, sunt at facilis doloremque nam totam, soluta esse tempore veritatis quibusdam deleniti quae quidem eos ducimus quos dignissimos, a magnam. Alias sit recusandae aperiam.
      Eveniet, optio et minus eum natus qui nemo veniam tempore maxime, ut non ad iusto. Alias perferendis assumenda placeat ut ad atque fugit in nemo sapiente, asperiores, aut, fugiat voluptate?
      Quae perspiciatis quos alias sint labore hic quia laborum minima fugiat velit reiciendis molestias, deleniti quisquam est recusandae iusto libero suscipit! Necessitatibus ratione quas alias voluptatibus, repellat quae aliquam delectus.
      Quis eius enim minima eligendi explicabo earum nemo dolor veniam doloremque, non atque quod veritatis animi, id ex. Voluptatibus enim reiciendis rem maxime ducimus quibusdam illum optio neque temporibus repudiandae.
      Quis numquam eveniet, beatae quaerat atque natus voluptatem dolore ab impedit vel, voluptatibus earum doloribus magnam reiciendis provident! Assumenda optio doloremque voluptatum. Assumenda libero harum distinctio ex ducimus a ut!
      Voluptates repudiandae laboriosam illum nam cum possimus eos quidem, ut iusto enim! Dolorem alias debitis, iste quo provident ullam! Recusandae optio officiis facere fugit inventore ipsum corporis quisquam at explicabo!
      Deserunt ex harum odit officiis illo neque obcaecati laboriosam nemo doloremque rem, necessitatibus iste perferendis consequuntur odio aut eius. Unde aliquid repellat exercitationem adipisci a, voluptatem perferendis. In, harum error.
      Consequuntur voluptas, porro natus molestiae consequatur enim culpa doloremque commodi accusamus doloribus exercitationem deserunt, optio dolorum animi, velit aliquam similique sint a dolorem voluptatibus aperiam tenetur molestias. Atque, consequuntur mollitia.
      Laudantium eum, ratione numquam perferendis suscipit magnam, quas hic aliquid eveniet incidunt qui ea excepturi similique sed minima harum, magni blanditiis rerum laboriosam nulla aspernatur asperiores. Eligendi omnis consequuntur voluptatibus.
      Velit, non! Itaque cum quos earum id illum nesciunt magni, excepturi ut. Dolore assumenda nemo qui natus deserunt? Rem ea ipsam eius nam suscipit sint velit exercitationem libero? Ex, repellat?
      Consectetur assumenda ipsam cumque dolor incidunt fuga laboriosam minima, libero culpa, distinctio, labore repudiandae itaque iusto alias temporibus facere. Nisi odit veniam facere dicta atque nam culpa dolores nobis. Saepe.
      Assumenda officiis ad modi voluptatum voluptatem maiores. Provident explicabo iusto repudiandae quia minus similique est aut fugiat quo soluta incidunt possimus, temporibus voluptas nam nostrum sequi praesentium dolorum impedit rem!
      Corrupti, maxime quam. Dolorum unde quae in exercitationem accusantium tempora cumque sit, assumenda, ducimus, commodi laborum beatae maxime? Officia et a earum qui repellat dolore molestiae. Nostrum magnam necessitatibus quibusdam!
      Quos, debitis veniam sint, facere libero ex labore, ducimus consequuntur veritatis a aliquid commodi omnis. Facilis, non maxime officiis sequi, quas vitae quisquam consequatur rerum beatae laboriosam quae enim! Ratione!
      Voluptate deleniti sequi ducimus vitae vel vero possimus, assumenda quae laboriosam quibusdam fugit inventore repellendus tenetur quasi quam omnis. Nisi non corporis rem impedit laboriosam voluptatem officia amet accusantium in.
      Ex corrupti voluptates quia at similique suscipit! Soluta ad deserunt voluptate, facere ipsam voluptatem, culpa omnis quia veniam voluptates distinctio totam quos, esse possimus nesciunt harum saepe! Repellendus, minus eaque?
      Dolorum fuga harum quos iste maxime optio corporis illo, illum esse tenetur voluptatum fugit voluptate quidem quam voluptatem doloremque impedit officia minus nobis et? Aliquid tenetur id quo pariatur sint.
      Vel neque mollitia eum ab aliquam molestiae nesciunt laudantium labore quos quam, quasi maxime quae sint repudiandae eveniet non tempore. Quia, ipsam corrupti? Unde facilis impedit deserunt, voluptate illum cum?
      Voluptatibus facilis sint id aperiam ab sapiente nobis? Quae dolores quisquam animi tempora consectetur doloribus totam placeat tenetur nemo, perferendis mollitia, necessitatibus dolor perspiciatis provident, culpa pariatur ullam aperiam. Alias.
      A voluptatibus nam quae assumenda doloribus enim sit accusantium repellendus quaerat itaque ut iure saepe nulla nostrum laboriosam optio similique fugiat soluta, laborum ab commodi atque. Rem iusto recusandae reprehenderit.
      Est optio voluptate ducimus, modi id minus laborum dolore laboriosam enim fugit blanditiis quidem tempore vel. Neque itaque, at voluptates praesentium repudiandae quaerat aut vero aperiam doloribus expedita ab id?
      Unde autem asperiores deserunt illum, minus ullam distinctio maiores aliquid facere, nostrum aspernatur aut ratione magnam. Magni maiores reiciendis dignissimos non, corrupti error quis doloremque mollitia assumenda corporis eaque aliquid.
      Suscipit dolor quasi minus dolorem, facilis, sunt hic quos aperiam consectetur ipsum rem odit fugiat alias officia ex. Voluptates obcaecati, iure praesentium fuga iste ab at totam. Amet, perspiciatis ad.
      Perferendis odit nemo quos corrupti maiores, voluptatem repellendus. Reprehenderit rem, laudantium delectus neque assumenda similique quisquam, voluptas autem quasi cumque adipisci quia repellendus obcaecati architecto! Laborum exercitationem repellendus animi quis?
      Nostrum atque, dolorum illo cumque libero laborum consequatur consectetur debitis. Sequi explicabo ratione molestias porro rerum animi aliquid, quos recusandae cupiditate aperiam quod ipsa natus veritatis neque. Fugit, incidunt sed.
      Reprehenderit id distinctio facere autem in commodi necessitatibus assumenda veniam porro, laudantium non voluptate hic, excepturi maiores. Voluptate quasi rem molestias sint modi reprehenderit nulla fugiat. Itaque quaerat libero quam.
      Impedit numquam modi nam quisquam culpa. Consectetur fugiat eveniet asperiores perferendis! Similique quis minima dolorem perspiciatis, mollitia architecto aperiam, ut fuga, libero quibusdam cupiditate obcaecati natus suscipit quisquam assumenda sunt?
      Perferendis temporibus iusto, architecto libero magnam sit nobis accusantium! Doloremque quo nostrum alias iure molestiae. Itaque, neque illo eos veritatis doloremque eveniet adipisci expedita iure. Repellendus saepe incidunt laboriosam adipisci.
      Doloribus, corporis! Asperiores illo earum, impedit in nostrum dolorum molestias voluptatibus ipsa minima, corporis voluptates mollitia sunt, enim dolor maiores architecto doloremque quas obcaecati saepe aspernatur. Ex minima molestias architecto!
      Animi debitis sit unde itaque pariatur quibusdam? Quos perspiciatis soluta officia iusto, fugiat quaerat accusamus fugit. Eaque suscipit veritatis, quasi facilis natus nemo aliquam iste neque iure omnis nihil voluptatum?
      Fugiat, ullam iste! Sit itaque, vero praesentium nemo quasi, eius dolores molestias soluta, officiis maiores laboriosam! Modi magni, incidunt praesentium enim quis maxime dolore quam quibusdam ad soluta. Earum, veniam.
      Necessitatibus fugit quas eaque eum magnam blanditiis obcaecati amet inventore, cumque aut numquam, vero a dignissimos molestiae officiis soluta delectus? Velit officia delectus error animi aut, ea amet asperiores dicta!
      Adipisci hic tempore beatae aspernatur ducimus? Itaque, tempora ea! Et harum architecto odit ipsum distinctio ea inventore, repellendus nisi dolores quia iure alias aliquid magni cum minima pariatur sint unde!
      Iusto error recusandae nesciunt asperiores quidem, quas ex reiciendis amet accusamus! Enim, dignissimos velit placeat doloribus praesentium qui hic iste est repellendus, minus tenetur aliquam eligendi repellat error quisquam doloremque.
      Eligendi omnis ullam error facilis totam, doloribus numquam fuga rerum voluptates sint expedita aut fugiat blanditiis similique soluta? Deserunt reprehenderit quo consequatur ipsam iusto voluptas cum fugiat eius atque sed?
      Distinctio qui culpa commodi placeat eius consectetur natus? Modi perspiciatis assumenda iste nulla dolore molestias, natus nemo accusantium repellat aliquam eligendi perferendis! Deserunt ullam quasi nam neque aliquam ratione in!
      Reiciendis adipisci rerum eius hic ratione vero sit aperiam consequuntur exercitationem nesciunt sequi iusto voluptatem perspiciatis recusandae ducimus enim delectus nulla, minus libero laudantium quisquam! Sapiente at eligendi quo maxime?
      Tempora sit ipsam beatae quia reiciendis, rerum ducimus laboriosam minus modi iusto veniam recusandae autem molestias possimus iste dignissimos mollitia atque, asperiores, adipisci consequatur accusantium esse! Eius minima reiciendis tempora.
      Illum ab animi omnis ratione debitis alias reprehenderit quos cupiditate cum asperiores, veniam autem, perspiciatis in hic nam aperiam sequi quidem voluptas consequuntur nobis dolore quis accusantium! Perspiciatis, voluptatibus neque?
      Eligendi quo, quod numquam, vitae error accusantium laboriosam, inventore ex cupiditate fugit officia? Placeat incidunt aliquid corrupti nisi laborum. Quibusdam in possimus cumque dolor ab sed provident vel repellendus sunt.
      Excepturi laborum nam similique minima nesciunt eligendi quod expedita distinctio, animi saepe. Ea incidunt eius quia voluptatem molestiae deserunt fugiat, quis mollitia, possimus aliquid cum repellat expedita? Amet, necessitatibus et.
      Itaque modi rerum numquam nihil necessitatibus dolorum tempore laboriosam ratione, perferendis, ipsum nam porro. Asperiores nemo tenetur nam eum consequuntur explicabo officiis expedita? Nam quod tenetur illum commodi suscipit ut.
      Voluptatem quidem laboriosam suscipit eligendi, possimus ex deserunt maiores culpa. Illum, itaque magni! Maxime, ea architecto eius nam explicabo nihil repudiandae. Rem, dicta tenetur et impedit blanditiis delectus asperiores laudantium.
      Odit ipsam reiciendis velit rerum quisquam accusamus eveniet assumenda ipsum, tempora numquam adipisci provident aliquid eos aperiam quia consequatur perspiciatis corrupti officiis ex molestias inventore vitae neque! Aliquam, aperiam voluptatum.
      Laudantium minus deserunt eum neque fugiat facere porro hic vitae, ducimus, necessitatibus ipsa unde voluptas harum excepturi maxime doloremque consequuntur maiores, nam voluptatem cupiditate laborum distinctio aliquid accusantium rem? Quia.
      Id sequi quo, libero ad repellendus temporibus et eum suscipit laudantium, consequuntur voluptates praesentium qui laborum omnis laboriosam voluptas. Nisi dolores, incidunt harum consectetur iure iusto accusantium numquam sed ex.
      Quaerat rem tempore aperiam ipsam, debitis non amet nostrum natus, laborum ullam incidunt at enim? Vitae, molestiae, aperiam molestias a rerum, ratione dolore facere eligendi obcaecati quaerat repellat animi repudiandae.
      Harum culpa iure dolorem quae, odio rem minus debitis mollitia deserunt saepe porro perspiciatis ipsa officia laborum quos in dolore. Doloribus aperiam minima nostrum, dicta quo obcaecati libero labore ducimus!
      Voluptatum temporibus cumque nulla sunt reprehenderit velit tempore, cupiditate labore nobis assumenda cum eligendi perspiciatis est, voluptatibus aspernatur esse beatae quidem accusamus quis? Officia nihil eveniet libero accusamus non labore.
      Voluptatum, ea vitae neque adipisci consequuntur eaque dolorum temporibus ex odit voluptatem velit, quia culpa accusamus possimus. Aliquid, vitae minus illum cupiditate vero iusto amet culpa nostrum aperiam, nam magni.
      Quos dignissimos veritatis suscipit atque cupiditate. Voluptates, eius? Neque possimus sunt quis obcaecati, facilis repudiandae omnis voluptates fugiat pariatur unde ut temporibus totam qui facere officiis delectus mollitia, perferendis blanditiis.
      Consectetur, eius. Corrupti repellendus laudantium delectus vero. Provident eaque dignissimos adipisci ipsa aliquam officiis molestias fugit ipsum tempora odio dolores voluptatibus natus rerum autem, nam eligendi similique repellendus ducimus eveniet?
      Ducimus tempore veniam dignissimos odio inventore, saepe debitis magnam expedita placeat unde sit enim animi impedit. Nostrum dignissimos, voluptate tempore, obcaecati commodi dolores provident consequuntur delectus doloribus rerum maiores et?
      Libero sint consequuntur doloremque illo veniam quidem, vel soluta dolorem saepe reprehenderit modi id enim quod in beatae recusandae omnis eius? Delectus pariatur animi eum totam nihil vitae laboriosam voluptate!
      Sint nisi necessitatibus pariatur unde repellendus quisquam a eveniet tempore quos! Quae quis perspiciatis delectus eligendi animi a voluptatum, mollitia rem consequuntur et? Quibusdam, facilis veritatis incidunt sint aliquid voluptas.
      Commodi tenetur quam, sit dolore corrupti sapiente, suscipit, minus beatae maiores delectus molestias numquam illum cumque quia aut consectetur veritatis! Reprehenderit voluptas, nisi minima totam ipsam quo quisquam ducimus tempore!
      Perferendis labore quae veniam iusto natus nam nisi quisquam beatae consequuntur, saepe expedita soluta voluptas, accusantium, quam quia eos provident cupiditate. Fugiat quae fugit amet cumque quidem, iure aperiam atque?
      Dolor dolores quaerat dignissimos est voluptatum nam perferendis id aliquid quis eaque exercitationem consectetur omnis repellat, corrupti debitis illum libero dolorem corporis, autem natus eligendi ullam suscipit accusantium. Quia, quae!
      Provident dolor qui temporibus eius dolorum adipisci, consectetur laborum amet quis rerum quidem aperiam eaque fugit, eum nostrum iure. Doloremque, porro commodi quod sapiente quis eveniet saepe quibusdam quas corporis!
      Minus explicabo perspiciatis magni dolor, non, nihil ducimus, aspernatur natus consectetur quasi facilis deserunt. Voluptas consectetur tempore explicabo. Sequi quasi earum obcaecati nemo ipsa excepturi minus ipsum officiis dolor fugit!
      Dolor repellendus maxime, odio quisquam tempore nam atque similique dolore minima provident cumque. Quos omnis, sequi autem ducimus nisi eligendi necessitatibus illo eum nobis temporibus, minima voluptatem perspiciatis ipsa! Aliquid.
      Impedit facilis esse libero? Quos voluptas dolor officiis odio atque facilis reiciendis eum iure in consequuntur repellat obcaecati aperiam laudantium ex necessitatibus nemo est facere, error deleniti? Quos, hic soluta?
      Nemo, sapiente enim! Iusto vel quaerat reprehenderit, accusantium obcaecati dolorem iste quos? Mollitia corporis minima, asperiores praesentium delectus consectetur possimus eum cupiditate magnam fugit temporibus, atque in fuga. Quam, natus.
      Quisquam porro ullam reiciendis facere explicabo error cupiditate quaerat iure ducimus unde enim, quos soluta, dolore exercitationem ut facilis eius officia obcaecati tempore sequi tenetur tempora. Architecto tempora adipisci maiores.
      Iure reiciendis nisi eaque officia dolorem debitis odit eligendi modi labore atque officiis doloribus nemo totam esse dignissimos, eum rem exercitationem aspernatur est. Eaque iure id fugit voluptate nisi. Deserunt!
      Esse iste, distinctio natus illum molestiae adipisci tempora consequatur consequuntur sunt saepe maiores laborum quis, eveniet, alias pariatur maxime necessitatibus quae. Fugit exercitationem minus illum minima recusandae accusamus rerum nisi.
      Delectus id facere dolor, corporis, aperiam deserunt sequi voluptatibus natus minima magnam placeat est eos voluptas dignissimos error cumque quae. Sequi distinctio inventore, ipsa officia sunt sed beatae tempora exercitationem.
      Quam quis similique praesentium! Ipsam laboriosam culpa temporibus minus nihil iste, quisquam consequuntur ab cupiditate eligendi ratione delectus distinctio porro maxime doloribus nam maiores accusantium optio velit vero at odit?
      Sequi, qui non alias maxime odio adipisci. Quo maiores tempore, omnis quis necessitatibus minima voluptates exercitationem asperiores quod eligendi, corrupti dolores perferendis, reprehenderit deleniti tenetur est qui nulla eveniet nemo!
      Veniam culpa distinctio repellat, eaque eos at eum ea quos similique rem? Quae sunt consectetur atque libero rerum soluta, mollitia quo impedit temporibus ducimus sequi enim, corporis odio itaque distinctio?
      Incidunt vero earum eligendi fugit suscipit saepe sequi eum! Repellendus perferendis qui, quos odit architecto recusandae consequuntur sunt tempore voluptatem tenetur atque dolores debitis! Commodi soluta delectus ullam temporibus accusantium.
      Aut temporibus, asperiores enim perferendis expedita officiis assumenda cum itaque quisquam neque, tenetur aperiam vel fuga accusantium similique! Cupiditate minima dolore labore iusto culpa voluptatibus sint vel quaerat praesentium minus!
      Sint laudantium quaerat sunt ratione totam recusandae. Quod, placeat. Recusandae aperiam, cum nihil laborum maiores harum voluptates odio animi ex doloribus alias ipsum corporis expedita laudantium mollitia. Veritatis, magni itaque.
      Ratione nemo et voluptatibus assumenda cumque libero asperiores ad numquam veritatis eos optio porro delectus ullam, neque incidunt rem ipsum cum eius qui! Perferendis perspiciatis vel odio praesentium doloribus esse!
      Voluptates totam necessitatibus obcaecati ut distinctio vitae, temporibus iure accusamus beatae sed. Magnam consectetur placeat nisi, recusandae debitis tempora culpa laudantium alias, quidem cum dolorem distinctio, quae quasi totam amet.
      Ipsum fugiat nemo fuga itaque deleniti, ipsam iure voluptas dicta non doloribus quisquam, facere repudiandae cum perspiciatis incidunt esse odit perferendis, iusto sint eum quo? Facilis et quaerat sed fugit?
      Repudiandae perspiciatis aspernatur rerum iusto vitae fuga! Provident tempore corrupti exercitationem quisquam natus hic omnis quod nulla aliquid praesentium voluptatem nesciunt recusandae sapiente obcaecati nemo quam aut, fugit velit. Numquam?
      Minus ad hic natus ratione dolor aliquam incidunt possimus architecto suscipit quidem, nobis quisquam laborum harum et mollitia. Hic, quasi quibusdam quod saepe omnis consectetur quaerat facere distinctio accusamus. Laboriosam.
      Sit omnis facere quis dolorem optio dolor fuga corporis. Sequi, voluptas perspiciatis voluptate beatae accusantium inventore. Sequi animi recusandae, unde fuga aspernatur in placeat quos officiis alias maxime illo deserunt!
     </div>
    </div>
  )
}

export default TnC